In [1]:
import pandas as pd 
import os 
from sqlalchemy import create_engine

In [2]:
engine = create_engine('sqlite:///inventory.db')

In [ ]:
for file in os.listdir('data'):
    if '.csv' in file:
        df = pd.read_csv('data/' + file)
        print(df.shape)
        ingest_db(df, file[:-4], engine)

(2372474, 16)
(12261, 9)
(5543, 10)
(206529, 9)
(224489, 9)
(12825363, 14)

In [4]:
def ingest_db(df, table_name, engine):
    df.to_sql(
        table_name,
        con=engine,
        if_exists='replace',
        index=False
    )

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("inventory.db")

pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

In [2]:
pd.read_sql(
    "PRAGMA table_info(sales)",
    conn
)

    cid            name    type  notnull dflt_value  pk
0     0     InventoryId    TEXT        0       None   0
1     1           Store  BIGINT        0       None   0
2     2           Brand  BIGINT        0       None   0
3     3     Description    TEXT        0       None   0
4     4            Size    TEXT        0       None   0
5     5   SalesQuantity  BIGINT        0       None   0
6     6    SalesDollars   FLOAT        0       None   0
7     7      SalesPrice   FLOAT        0       None   0
8     8       SalesDate    TEXT        0       None   0
9     9          Volume   FLOAT        0       None   0
10   10  Classification  BIGINT        0       None   0
11   11       ExciseTax   FLOAT        0       None   0
12   12        VendorNo  BIGINT        0       None   0
13   13      VendorName    TEXT        0       None   0

In [3]:
pd.read_sql(
    "PRAGMA table_info(purchases)",
    conn
)

    cid            name    type  notnull dflt_value  pk
0     0     InventoryId    TEXT        0       None   0
1     1           Store  BIGINT        0       None   0
2     2           Brand  BIGINT        0       None   0
3     3     Description    TEXT        0       None   0
4     4            Size    TEXT        0       None   0
5     5    VendorNumber  BIGINT        0       None   0
6     6      VendorName    TEXT        0       None   0
7     7        PONumber  BIGINT        0       None   0
8     8          PODate    TEXT        0       None   0
9     9   ReceivingDate    TEXT        0       None   0
10   10     InvoiceDate    TEXT        0       None   0
11   11         PayDate    TEXT        0       None   0
12   12   PurchasePrice   FLOAT        0       None   0
13   13        Quantity  BIGINT        0       None   0
14   14         Dollars   FLOAT        0       None   0
15   15  Classification  BIGINT        0       None   0

In [4]:
pd.read_sql(
    "PRAGMA table_info(vendor_invoice)",
    conn
)

   cid          name    type  notnull dflt_value  pk
0    0  VendorNumber  BIGINT        0       None   0
1    1    VendorName    TEXT        0       None   0
2    2   InvoiceDate    TEXT        0       None   0
3    3      PONumber  BIGINT        0       None   0
4    4        PODate    TEXT        0       None   0
5    5       PayDate    TEXT        0       None   0
6    6      Quantity  BIGINT        0       None   0
7    7       Dollars   FLOAT        0       None   0
8    8       Freight   FLOAT        0       None   0
9    9      Approval    TEXT        0       None   0

In [5]:
pd.read_sql(
    "PRAGMA table_info(sales)",
    conn
)

    cid            name    type  notnull dflt_value  pk
0     0     InventoryId    TEXT        0       None   0
1     1           Store  BIGINT        0       None   0
2     2           Brand  BIGINT        0       None   0
3     3     Description    TEXT        0       None   0
4     4            Size    TEXT        0       None   0
5     5   SalesQuantity  BIGINT        0       None   0
6     6    SalesDollars   FLOAT        0       None   0
7     7      SalesPrice   FLOAT        0       None   0
8     8       SalesDate    TEXT        0       None   0
9     9          Volume   FLOAT        0       None   0
10   10  Classification  BIGINT        0       None   0
11   11       ExciseTax   FLOAT        0       None   0
12   12        VendorNo  BIGINT        0       None   0
13   13      VendorName    TEXT        0       None   0

In [6]:
pd.read_sql(
    "PRAGMA table_info(purchases)",
    conn
)

    cid            name    type  notnull dflt_value  pk
0     0     InventoryId    TEXT        0       None   0
1     1           Store  BIGINT        0       None   0
2     2           Brand  BIGINT        0       None   0
3     3     Description    TEXT        0       None   0
4     4            Size    TEXT        0       None   0
5     5    VendorNumber  BIGINT        0       None   0
6     6      VendorName    TEXT        0       None   0
7     7        PONumber  BIGINT        0       None   0
8     8          PODate    TEXT        0       None   0
9     9   ReceivingDate    TEXT        0       None   0
10   10     InvoiceDate    TEXT        0       None   0
11   11         PayDate    TEXT        0       None   0
12   12   PurchasePrice   FLOAT        0       None   0
13   13        Quantity  BIGINT        0       None   0
14   14         Dollars   FLOAT        0       None   0
15   15  Classification  BIGINT        0       None   0

In [5]:
query = """
SELECT
VendorNumber,
VendorName,
SUM(Dollars) AS PurchaseAmount,
SUM(Quantity) AS PurchaseQty

FROM purchases

GROUP BY VendorNumber, VendorName
"""

vendor_summary = pd.read_sql(query, conn)

vendor_summary.head()

,VendorNumber,VendorName,PurchaseAmount,PurchaseQty
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",5630.88,328
1,54,AAPER ALCOHOL & CHEMICAL CO,105.07,1
2,60,ADAMBA IMPORTS INTL INC,76770.25,4732
3,105,ALTAMAR BRANDS LLC,11706.20,332
4,200,AMERICAN SPIRITS EXCHANGE,1205.16,132

In [4]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("inventory.db")

In [6]:
vendor_summary.shape

(129, 4)

In [7]:
top_vendors = vendor_summary.sort_values(
    by="PurchaseAmount",
    ascending=False
)

top_vendors.head(10)

     VendorNumber                   VendorName  PurchaseAmount  PurchaseQty
42           3960  DIAGEO NORTH AMERICA INC        50959796.85      5459788
44           4425        MARTIGNETTI COMPANIES     27821473.91      2637275
98          12546  JIM BEAM BRANDS COMPANY         24203151.05      2737165
102         17035  PERNOD RICARD USA               24124091.56      1647558
7             480  BACARDI USA INC                 17624378.72      1427075
16           1392  CONSTELLATION BRANDS INC        15573917.90      2325892
12           1128  BROWN-FORMAN CORP               13529433.08      1006122
83           9165  ULTRA BEVERAGE COMPANY LLP      13210613.93      1077527
36           3252  E & J GALLO WINERY              12289608.09      1858260
86           9552  M S WALKER INC                  10935817.30      1372841

In [8]:
import matplotlib.pyplot as plt

top10 = top_vendors.head(10)

plt.figure(figsize=(12,6))
plt.bar(top10["VendorName"], top10["PurchaseAmount"])

plt.xticks(rotation=90)
plt.title("Top 10 Vendors by Purchase Amount")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'